### ISSUE TITLE
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating GPU_0_bfc

### ISSUE THREAD

**Issue by Anery** [thunlp/OpenNRE#157]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py",
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py",
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py",
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating GPU_0_bfc
	 [[{{node gpu_0/gradients/gpu_0/attention/strided_slice_1194_grad/StridedSli
Hint: If you want to see a list of allocated tensors when OOM happens, add report_te

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_demo.py", line 110, in <module>
    framework.train(model, model_name=dataset_name + "_" + model.encoder + "_" + mod
  File "/home/DS_RE/OpenNRE/nrekit/framework.py", line 179, in train
    iter_loss, iter_logit, _train_op, iter_label = self.one_step_multi_models(self.s
  File "/home/DS_RE/OpenNRE/nrekit/framework.py", line 93, in one_st
    result = sess.run(run_array, feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py",
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py",
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py",
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py",
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating GPU_0_bfc
	 [[node gpu_0/gradients/gpu_0/attention/strided_slice_1194_grad/StridedSlice
Hint: If you want to see a list of allocated tensors when OOM happens, add report_te

Caused by op 'gpu_0/gradients/gpu_0/attention/strided_slice_1194_grad/StridedSliceGr
  File "train_demo.py", line 110, in <module>
    framework.train(model, model_name=dataset_name + "_" + model.encoder + "_" + mod
  File "/home/DS_RE/OpenNRE/nrekit/framework.py", line 142, in train
    tower_grads.append(optimizer.compute_gradients(cur_model.loss()))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.
    unconnected_gradients)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.
    return grad_fn()  # Exit early
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_grad.py",
    shrink_axis_mask=op.get_attr("shrink_axis_mask")), None, None, None
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.p
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_li
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", 
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", 
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'gpu_0/attention/strided_slice_1194', defined 
  File "train_demo.py", line 110, in <module>
    framework.train(model, model_name=dataset_name + "_" + model.encoder + "_" + mod
  File "/home/DS_RE/OpenNRE/nrekit/framework.py", line 141, in train
    cur_model = model(self.train_data_loader, self.train_data_loader.batch_size // g
  File "train_demo.py", line 57, in __init__
    self._train_logit, train_repre = nrekit.network.selector.bag_attention(x_train, 
  File "/home/DS_RE/OpenNRE/nrekit/network/selector.py", line 42, in
    bag_hidden_mat = x[scope[i][0]:scope[i][1]]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", 
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", 
    shrink_axis_mask=shrink_axis_mask)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.p
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_li
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", 
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", 
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with sh
	 [[node gpu_0/gradients/gpu_0/attention/strided_slice_1194_grad/StridedSlice
Hint: If you want to see a list of allocated tensors when OOM happens, add report_t

出现了OOM错误？网上说是batch_size过大，但我把framework里的默认160改成64还是不行，请问这是什么原因？初学者，还请多指教，谢谢！

**Comment by Anery** [comment]
It happens again...

**Comment by MrSchnappi** [comment]
You speak my language!
