### ISSUE TITLE
"TypeError: Object of type 'bytes' is not JSON serializable" in test_demo.py

### ISSUE THREAD

**Issue by mrazizi** [thunlp/OpenNRE#170]
Hi,
When running test_demo.py with nyt dataset, when test is finished and data is going to be written in a json file, the following error occurs:

```
[TEST] auc: 0.2378905545480236
Finish testing
Traceback (most recent call last):
  File "test_demo.py", line 102, in <module>
    json.dump(pred_result, outfile)
  File "/usr/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.6/json/encoder.py", line 428, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

<br>

My proposed solution for this problem is to use **ujson** library to dump the json file. So the the following changes should be applied:

- importing the **ujson** library:
`import ujson`

- using  **ujson** library to dump json file:
change line 102 of test_demo.py from ` json.dump(pred_result, outfile)` to ` ujson.dump(pred_result, outfile)`

**Comment by qyccc** [comment]
in framework.py 
in `pred_result.append({"score": float(iter_logit[idx][rel]), "entpair": batch_data['entpair'][idx].encode('utf-8'), "relation": rel})` lines
delete` .encode('utf-8') `after `batch_data['entpair'][idx]`
in python3 then it can work!
