### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by GhadaAlfattni** [thunlp/OpenNRE#172]
Hi
I am trying to run the code on my own data and this is what I am getting

```
Loading data file...
Finish loading
Loading word vector file...
Finish loading
Elimiating case sensitive problem...
Traceback (most recent call last):
  File "train_demo.py", line 19, in <module>
    shuffle=True)
  File "/Users/ghada/Desktop/OpenNRE/nrekit/data_loader.py", line 248, in __init__
    self.ori_data[i]['tail']['word'] = self.ori_data[i]['tail']['word'].lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

any advice on how to solve it?

**Comment by GhadaAlfattni** [comment]
It seems I know the reason now.

I have some NULLs in the data, I will try again once I removed them

**Comment by GhadaAlfattni** [comment]
it is working now
