### ISSUE TITLE
安装后import失败

### ISSUE THREAD

**Issue by lk1983823** [thunlp/OpenNRE#203]
如下:
>>> import opennre
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lukuan/lk_git/OpenNRE/opennre/__init__.py", line 5, in <module>
    from .pretrain import check_root, get_model, download_glove, download_bert_base_uncased
  File "/home/lukuan/lk_git/OpenNRE/opennre/pretrain.py", line 1, in <module>
    from . import encoder
  File "/home/lukuan/lk_git/OpenNRE/opennre/encoder/__init__.py", line 5, in <module>
    from .cnn_encoder import CNNEncoder
  File "/home/lukuan/lk_git/OpenNRE/opennre/encoder/cnn_encoder.py", line 7, in <module>
    from .base_encoder import BaseEncoder
  File "/home/lukuan/lk_git/OpenNRE/opennre/encoder/base_encoder.py", line 6, in <module>
    from ..tokenization import WordTokenizer
  File "/home/lukuan/lk_git/OpenNRE/opennre/tokenization/__init__.py", line 7, in <module>
    from .basic_tokenizer import BasicTokenizer
  File "/home/lukuan/lk_git/OpenNRE/opennre/tokenization/basic_tokenizer.py", line 22, in <module>
    from .utils import (convert_to_unicode,
  File "/home/lukuan/lk_git/OpenNRE/opennre/tokenization/utils.py", line 33
    return unicodedata.category(char).startswith("P"):
                                                     ^
SyntaxError: invalid syntax
我的python版本是3.6.7 请问这是怎么回事? 谢谢

**Comment by gaotianyu1350** [comment]
Hi! This is a merge bug and has been fixed now. Thanks for the reminder!
