### ISSUE TITLE
建议: opennre的安装前明确tensorflow\cuda version\cuda的支持版本

### ISSUE THREAD

**Issue by lk1983823** [thunlp/OpenNRE#204]
第一安装的时候, 我的tensorflow版本是2.0. import opennre的是出现如下错误:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lukuan/lk_git/OpenNRE/opennre/__init__.py", line 5, in <module>
    from .pretrain import check_root, get_model, download_glove, download_bert_base_uncased
  File "/home/lukuan/lk_git/OpenNRE/opennre/pretrain.py", line 1, in <module>
    from . import encoder
  File "/home/lukuan/lk_git/OpenNRE/opennre/encoder/__init__.py", line 7, in <module>
    from .bert_encoder import BERTEncoder, BERTEntityEncoder
  File "/home/lukuan/lk_git/OpenNRE/opennre/encoder/bert_encoder.py", line 5, in <module>
    from transformers import BertModel, BertTokenizer
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/transformers/__init__.py", line 104, in <module>
    from .modeling_tf_utils import TFPreTrainedModel, TFSharedEmbeddings, TFSequenceSummary
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/transformers/modeling_tf_utils.py", line 34, in <module>
    class TFPreTrainedModel(tf.keras.Model):
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/transformers/modeling_tf_utils.py", line 54, in TFPreTrainedModel
    dummy_inputs = tf.constant(DUMMY_INPUTS)  # dummy inputs to build the network
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 95, in convert_to_eager_tensor
    ctx.ensure_initialized()
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 492, in ensure_initialized
    self._context_handle = pywrap_tensorflow.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
`
我的cuda版本是 10.0, 驱动是 NVIDIA-SMI 410.48. 满足tensorflow的要求.(不知道为什么会报这个错误).
随后,我降级tensorflow-gpu为1.13.1以后, import opennre没有问题了.

**Comment by gaotianyu1350** [comment]
现在应该已经没有tensorflow的依赖啦，你可以再试一试～

**Comment by lk1983823** [comment]
> 现在应该已经没有tensorflow的依赖啦，你可以再试一试～

还有一个问题就是 你的requirements.txt里面 直接写torch 1.3是不行的. 我默认pip安装的时候 就错装了版本, 建议有一个torch安装的具体方案(根据不同用户的cuda版本). 否则, cuda.available() 就成了false.

**Comment by benbijituo** [comment]
torch1.3在有些cuda版本上没办法用gpu。是不是考虑把这个torch版本要求改成1.0或者1.2

**Comment by gaotianyu1350** [comment]
torch版本的话可以根据自己的需要/cuda版本调整。
