### ISSUE TITLE
改成cpu可以使用的方法

### ISSUE THREAD

**Issue by qianlanwyd** [thunlp/OpenNRE#207]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wyd/OpenNRE/opennre/pretrain.py", line 77, in get_model
    m.load_state_dict(torch.load(ckpt)['state_dict'])
  File "/home/maxiao/.local/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/maxiao/.local/lib/python3.6/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
  File "/home/maxiao/.local/lib/python3.6/site-packages/torch/serialization.py", line 576, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/maxiao/.local/lib/python3.6/site-packages/torch/serialization.py", line 155, in default_restore_location
    result = fn(storage, location)
  File "/home/maxiao/.local/lib/python3.6/site-packages/torch/serialization.py", line 131, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/maxiao/.local/lib/python3.6/site-packages/torch/serialization.py", line 115, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by qianlanwyd** [comment]
将所有的torch.load(ckpt)改成torch.load(ckpt,maplocation='cpu')即可

**Comment by RickChina** [comment]
> 将所有的torch.load(ckpt)改成torch.load(ckpt,maplocation='cpu')即可

map_location='cpu'

**Comment by gaotianyu1350** [comment]
Now codes should be able to run using CPU.
