### ISSUE TITLE
import opennre出错

### ISSUE THREAD

**Issue by lyj-eternity** [thunlp/OpenNRE#216]
>>> import opennre
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\liuyingjie\IdeaProjects\OpenNRE\opennre\__init__.py", line 5, in <module>
    from .pretrain import check_root, get_model, download_glove, download_bert_base_uncased
  File "C:\Users\liuyingjie\IdeaProjects\OpenNRE\opennre\pretrain.py", line 10, in <module>
    default_root_path = os.path.join(os.getenv('HOME'), '.opennre')
  File "C:\Users\liuyingjie\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
这是怎么回事？

**Comment by VergessenWang** [comment]
Maybe it doesn't support windows OS, I have the same problem ：(

**Comment by gaotianyu1350** [comment]
It seems that you are using Windows. For now, we have only tested our package on Linux. Technically it should also work on Windows, yet some minor changes shall be made.
