### ISSUE TITLE
执行测试脚本报错：RuntimeError: error executing torch_shm_manager

### ISSUE THREAD

**Issue by longmingg** [thunlp/OpenNRE#230]
执行测试脚本python example/train_wiki80_cnn_softmax.py
然后会报如下错误: RuntimeError: error executing torch_shm_manager at "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99
然后会一直卡住

想请问一下这是什么情况，软件环境好像都没有问题，是内存配置的原因么，我是在mac上做的测试，选择的cpu模式，期待您的回复！

具体日志如下：
Initializing hyperparameters...
Finished!
Initializing word embedding with word2vec...
Finished!
=== Epoch 0 train ===
  0%|                                                       | 0/1575 [00:00<?, ?it/s]Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: error executing torch_shm_manager at "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99
Traceback (most recent call last):
  File "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: error executing torch_shm_manager at "/Users/longminggang/anaconda3/envs/deepkeTest/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99

**Comment by gaotianyu1350** [comment]
这个看起来是pytorch在mac上的问题，因为我没有在mac上测试过所以不太清楚。

建议使用linux+gpu环境运行工具包

**Comment by zheng-yan-max** [comment]
请问问题解决了吗？如果有解决方案，请告知我一下，十分感谢。
