### ISSUE TITLE
import opennre时产生TypeError: expected str错误

### ISSUE THREAD

**Issue by joy19952019** [thunlp/OpenNRE#260]
如题，请各位小伙伴帮忙看看~
详细报错：
import opennre
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\SOFTWARE\anacondaRoute\lib\site-packages\opennre-0.1-py3.7.egg\opennre\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\SOFTWARE\anacondaRoute\lib\site-packages\opennre-0.1-py3.7.egg\opennre\pretrain.py", line 11, in <module>
  File "C:\SOFTWARE\anacondaRoute\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by gaotianyu1350** [comment]
目前opennre还不支持windows，如果需要在windows下运行的话，请尝试用WSL运行，否则可能有路径问题
