### ISSUE TITLE
RuntimeError: DefaultCPUAllocator: can't allocate memory

### ISSUE THREAD

**Issue by CatarinaPC** [thunlp/OpenNRE#270]
I was running the example code in example/train_bag_pcnn_att.py

I replaced the paths used to load the variables `word2id` and `word2vec` with files that I created from a fasttext .vec file.
I got an error: ` 'Object arrays cannot be loaded when allow_pickle=False'` on:
`word2vec = np.load(word2vec_path)`
I changed it to:
`word2vec = np.load(word2vec_path, allow_pickle=True) `and that error got fixed.

From reading online its an error related to keras and numpy.

<br>

**I ran the code again and got another error (which is the topic of this issue):**

```
Traceback (most recent call last):
  File "/home/catarinapc/distant-re/src/models/train_model.py", line 14, in <module>
    run()
  File "/home/catarinapc/distant-re/src/models/train_model.py", line 12, in run
    word2vec_path='../../models/word_embeddings/fasttext/wiki.fr_mat.npy')
  File "/home/catarinapc/distant-re/src/models/bag_pcnn_att_model.py", line 37, in train
    dropout=0.5
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/opennre-0.1-py3.6.egg/opennre/encoder/pcnn_encoder.py", line 39, in __init__
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/opennre-0.1-py3.6.egg/opennre/encoder/base_encoder.py", line 56, in __init__
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 109, in __init__
    self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 5312573229600 bytes. Error code 12 (Cannot allocate memory)
```
On:

```
        # Define the sentence encoder
        sentence_encoder = opennre.encoder.PCNNEncoder(
            token2id=word2id,
            max_length=128,
            word_size=50,
            position_size=5,
            hidden_size=230,
            blank_padding=True,
            kernel_size=3,
            padding_size=1,
            word2vec=word2vec,
            dropout=0.5
        )
```

How should I proceed?

**Comment by CatarinaPC** [comment]
I tried the same code but using the glove embeddings in the directory `pretrain` and the error does not occur. So it's probably something related to my .npy and .json word embedding files

**Comment by gaotianyu1350** [comment]
It seems to be related to the numpy file. 5312573229600 is around 5T memory. Maybe the numpy file is corrupted.

**Comment by CatarinaPC** [comment]
I tried a different code do generate the .npy and .json files.

That error does not occur anymore, but now I have a different one and I don't know what is causing it:

```
Traceback (most recent call last):
  File "/home/catarinapc/distant-re/src/models/train_model.py", line 21, in <module>
    run()
  File "/home/catarinapc/distant-re/src/models/train_model.py", line 19, in run
    word2vec_path='../../models/word_embeddings/fasttext/fasttext_embedding_en.npy')
  File "/home/catarinapc/distant-re/src/models/bag_pcnn_att_model.py", line 37, in train
    dropout=0.5
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/opennre-0.1-py3.6.egg/opennre/encoder/pcnn_encoder.py", line 39, in __init__
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/opennre-0.1-py3.6.egg/opennre/encoder/base_encoder.py", line 65, in __init__
RuntimeError: The size of tensor a (1152452) must match the size of tensor b (1152449) at non-singleton dimension 0
```

**Comment by CatarinaPC** [comment]
I was adding [UNK] =0 to my word2id.json.

I removed it because I saw on base_encoder.py this and for some reason thought it made sense:

```
if word2vec is not None:
            logging.info("Initializing word embedding with word2vec.")
            word2vec = torch.from_numpy(word2vec)
            if self.num_token == len(word2vec) + 2:            
                unk = torch.randn(1, self.word_size) / math.sqrt(self.word_size)
                blk = torch.zeros(1, self.word_size)
                self.word_embedding.weight.data.copy_(torch.cat([word2vec, unk, blk], 0))
            else:
                self.word_embedding.weight.data.copy_(word2vec)

```

Now the code runs past the PCNNEncoder initialization but I have a new error:

```
2020-08-19 16:16:20,023 - root - INFO - Initializing word embedding with word2vec.
=== Epoch 0 train ===
  0%|          | 0/1112 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/catarinapc/distant-re/src/models/train_model.py", line 21, in <module>
    run()
  File "/home/catarinapc/distant-re/src/models/train_model.py", line 19, in run
    word2vec_path='../../models/word_embeddings/fasttext/fasttext_embedding_en.npy')
  File "/home/catarinapc/distant-re/src/models/bag_pcnn_att_model.py", line 57, in train
    framework.train_model('auc')
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/opennre-0.1-py3.6.egg/opennre/framework/bag_re.py", line 121, in train_model
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/opennre-0.1-py3.6.egg/opennre/model/bag_attention.py", line 96, in forward
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/opennre-0.1-py3.6.egg/opennre/encoder/pcnn_encoder.py", line 70, in forward
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 257, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [230, 60, 3], expected input[38, 310, 128] to have 60 channels, but got 310 channels instead
```

**Comment by gaotianyu1350** [comment]
I see ... What is the dimension of your provided embedding? You need to assign `word_size=YOUR WORD EMBEDDING DIMENSION` in `opennre.encoder.PCNNEncoder` constructor function.

**Comment by CatarinaPC** [comment]
Well according to the fasttext website:

_We are publishing pre-trained word vectors for 294 languages, trained on Wikipedia using fastText. **These vectors in dimension 300** were obtained using the skip-gram model described in Bojanowski et al. (2016) with default parameters._

So, from this I would say 300 but based on the previous error it said `but got 310 channels instead`

**Comment by gaotianyu1350** [comment]
You should use 300. The additional 10 is for position embeddings.

**Comment by CatarinaPC** [comment]
I used 300 and don't get the error anymore, thank you.

However now I get a CUDA out of memory:

```
2020-08-20 18:32:53,042 - root - INFO - Initializing word embedding with word2vec.
=== Epoch 0 train ===
  0%|                                                                           | 0/1169 [00:00<?, ?it/s, acc=0, loss=3.6, pos_acc=0]
Traceback (most recent call last):
  File "train_model.py", line 31, in <module>
    run()
  File "train_model.py", line 14, in run
    word2vec_path='../../models/word_embeddings/fasttext/wiki.fr_mat.npy')
  File "../models/bag_pcnn_att_model.py", line 57, in train
    framework.train_model('auc')
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/opennre-0.1-py3.6.egg/opennre/framework/bag_re.py", line 140, in train_model
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/optim/sgd.py", line 99, in step
    d_p = d_p.add(p, alpha=weight_decay)
RuntimeError: CUDA out of memory. Tried to allocate 1.29 GiB (GPU 0; 3.95 GiB total capacity; 2.58 GiB already allocated; 170.88 MiB free; 2.58 GiB reserved in total by PyTorch)
```

Do you have any idea on how to fix it?

**Comment by gaotianyu1350** [comment]
I think it's just a simple GPU out of memory error. You can try smaller batch size or try to use a GPU with larger memory.
