### ISSUE TITLE
Infer BagAttention model

### ISSUE THREAD

**Issue by CatarinaPC** [thunlp/OpenNRE#279]
Following the example in the homepage:

```
>>> import opennre
>>> model = opennre.get_model('wiki80_cnn_softmax')
>>> model.infer({'text': 'He was the son of Máel Dúin mac Máele Fithrich, and grandson of the high king Áed Uaridnach (died 612).', 'h': {'pos': (18, 46)}, 't': {'pos': (78, 91)}})
('father', 0.5108704566955566)
```

I want to load a model I trained which is bag pcnn+att and then use the `infer` function to predict relationships, just like in the example.

Looking at the `bag_attention.py`, to the function `infer()`:

```
    def infer(self, bag):
        """
        Args:
            bag: bag of sentences with the same entity pair
                [{
                  'text' or 'token': ..., 
                  'h': {'pos': [start, end], ...}, 
                  't': {'pos': [start, end], ...}
                }]
        Return:
            (relation, score)
        """
```

I only need to pass a bag of sentences for the same entity pair and it will return the relation and its score.

So, _first_ I loaded my model, as I previously did, and it appears to match what is done in the `load_model()` function in `pretrain.py`, _then_ I do infer over the model (in this case with only one sentence in the bag):

```
model_name = "v1_pcnn_att"

model_dir_path = "../../models/bag_pcnn_att/"

rel2id_path = "../../datasets/processed/v1/rel2id.json"
train_path = "../../datasets/processed/v1/train_sentences.txt"
dev_path = "../../datasets/processed/v1/dev_sentences.txt"
test_path = "../../datasets/processed/v1/test_sentences.txt"
word2id_path = "../../models/word_embeddings/fasttext/wiki.fr_word2id.json"
word2vec_path = "../../models/word_embeddings/fasttext/wiki.fr_mat.npy"
max_epoch = 30

ckpt = model_dir_path + '{}.pth.tar'.format(model_name)

word2id = json.load(open(word2id_path))
word2vec = np.load(word2vec_path, allow_pickle=True)

rel2id = json.load(open(rel2id_path))

# Define the sentence encoder
sentence_encoder = opennre.encoder.PCNNEncoder(
    token2id=word2id,
    max_length=128,
    word_size=300,
    position_size=5,
    hidden_size=230,
    blank_padding=True,
    kernel_size=3,
    padding_size=1,
    word2vec=word2vec,
    dropout=0.5
)

# Define the model
model = opennre.model.BagAttention(sentence_encoder, len(rel2id), rel2id)

model.load_state_dict(torch.load(ckpt, map_location='cpu')['state_dict'])

print(model.infer([{"text": "L' hôtel Spoelberch de Lovenjoul est un ancien hôtel particulier situé au 23 rue du Connétable à Chantilly , dans l' Oise .",
               "h": { "pos": [3, 32]}, 
               "t": {"pos": [97, 106]}}]))

```

I get this error:

```
/home/catarinapc/distant-re/venv/bin/python /home/catarinapc/distant-re/src/models/infer_model_test.py
2020-08-27 01:57:30,300 - root - INFO - Initializing word embedding with word2vec.
Traceback (most recent call last):
  File "/home/catarinapc/distant-re/src/models/infer_model_test.py", line 48, in <module>
    "t": {"pos": [97, 106]}}]))
  File "/home/catarinapc/OpenNRE/opennre/model/bag_attention.py", line 47, in infer
    token, pos1, pos2, mask = self.tokenizer(item['text'], 
  File "/home/catarinapc/distant-re/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'BagAttention' object has no attribute 'tokenizer'
```

How should I proceed?

**Comment by CatarinaPC** [comment]
BTW

If I change the function `infer()` in `bag_attention.py` from:

```
        for item in bag:
            if 'text' in item:
                token, pos1, pos2, mask = self.tokenizer(item['text'], 
                    item['h']['pos'], item['t']['pos'], is_token=False, padding=True)
            else:
                token, pos1, pos2, mask = self.tokenizer(item['token'], 
                    item['h']['pos'], item['t']['pos'], is_token=True, padding=True)
```

to have `self.sentence_encoder.tokenizer` instead of `self.tokenizer`:

```
        for item in bag:
            if 'text' in item:
                token, pos1, pos2, mask = self.sentence_encoder.tokenizer(item['text'], 
                    item['h']['pos'], item['t']['pos'], is_token=False, padding=True)
            else:
                token, pos1, pos2, mask = self.sentence_encoder.tokenizer(item['token'], 
                    item['h']['pos'], item['t']['pos'], is_token=True, padding=True)
```

I get another error:

```
/home/catarinapc/distant-re/venv/bin/python /home/catarinapc/distant-re/src/models/infer_model_test.py
2020-08-27 02:09:11,530 - root - INFO - Initializing word embedding with word2vec.
Traceback (most recent call last):
  File "/home/catarinapc/distant-re/src/models/infer_model_test.py", line 48, in <module>
    "t": {"pos": [97, 106]}}]))
  File "/home/catarinapc/OpenNRE/opennre/model/bag_attention.py", line 48, in infer
    item['h']['pos'], item['t']['pos'], is_token=False, padding=True)
TypeError: 'WordTokenizer' object is not callable
```

**Comment by gaotianyu1350** [comment]
Hi, thanks for pointing this out. It is a bug in `infer` of `bag_attention`. It has been fixed in the latest update.
