### ISSUE TITLE
Error while importing TACRED pretrained model

### ISSUE THREAD

**Issue by lorelupo** [thunlp/OpenNRE#286]
Hello, 

`model = opennre.get_model('tacred_bert_softmax')` returns some logs that look like an error:

````
2020-09-09 16:12:41,492 - transformers.tokenization_utils_base - INFO - Model name '/root/.opennre/pretrain/bert-base-uncased' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, TurkuNLP/bert-base-finnish-cased-v1, TurkuNLP/bert-base-finnish-uncased-v1, wietsedv/bert-base-dutch-cased). Assuming '/root/.opennre/pretrain/bert-base-uncased' is a path, a model identifier, or url to a directory containing tokenizer files.
2020-09-09 16:12:41,497 - transformers.tokenization_utils_base - INFO - Didn't find file /root/.opennre/pretrain/bert-base-uncased/added_tokens.json. We won't load it.
2020-09-09 16:12:41,498 - transformers.tokenization_utils_base - INFO - Didn't find file /root/.opennre/pretrain/bert-base-uncased/special_tokens_map.json. We won't load it.
2020-09-09 16:12:41,500 - transformers.tokenization_utils_base - INFO - Didn't find file /root/.opennre/pretrain/bert-base-uncased/tokenizer_config.json. We won't load it.
2020-09-09 16:12:41,506 - transformers.tokenization_utils_base - INFO - Didn't find file /root/.opennre/pretrain/bert-base-uncased/tokenizer.json. We won't load it.
2020-09-09 16:12:41,508 - transformers.tokenization_utils_base - INFO - loading file /root/.opennre/pretrain/bert-base-uncased/vocab.txt
2020-09-09 16:12:41,509 - transformers.tokenization_utils_base - INFO - loading file None
2020-09-09 16:12:41,510 - transformers.tokenization_utils_base - INFO - loading file None
2020-09-09 16:12:41,512 - transformers.tokenization_utils_base - INFO - loading file None
2020-09-09 16:12:41,514 - transformers.tokenization_utils_base - INFO - loading file None
````

Could you help me to understand these logs and, in case it is an actual error, help me to fix them please?

**Comment by gaotianyu1350** [comment]
These are not errors. These are just some auxiliary tokenization files of hugginface that OpenNRE does not need. You can simply ignore these logs.

**Comment by aishwaryanr** [comment]
had the same issue and couldn't load the model with this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/OpenNRE/opennre/pretrain.py", line 140, in get_model
    m.load_state_dict(torch.load(ckpt, map_location='cpu')['state_dict'])
  File "/Users/OpenNRE/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SoftmaxNN:
	Unexpected key(s) in state_dict: "sentence_encoder.bert.embeddings.position_ids".
