### ISSUE TITLE
想请问关于NYT10数据集的问题

### ISSUE THREAD

**Issue by UUUZ** [thunlp/OpenNRE#294]
在运行example中的pcnn的训练时，使用了nyt10的数据集，但是出现了以下情况
Traceback (most recent call last):
  File "D:/Compiler/Github/OpenNRE/example/train_bag_pcnn_att.py", line 101, in <module>
    framework = opennre.framework.BagRE(
  File "D:\Compiler\Github\OpenNRE\opennre\framework\bag_re.py", line 30, in __init__
    self.train_loader = BagRELoader(
  File "D:\Compiler\Github\OpenNRE\opennre\framework\data_loader.py", line 265, in BagRELoader
    dataset = BagREDataset(path, rel2id, tokenizer, entpair_as_bag=entpair_as_bag, bag_size=bag_size)
  File "D:\Compiler\Github\OpenNRE\opennre\framework\data_loader.py", line 165, in __init__
    self.weight[self.rel2id[item['relation']]] += 1.0
KeyError: '/sports/sports_team_location/teams'

出现错误的句子：self.weight[self.rel2id[item['relation']]] += 1.0
我在rel2id.json中也并没有找到这个关系的键，请问为什么会出现这样的情况呢？
本人是NLP初学者，如果问了什么傻问题很抱歉。

**Comment by gaotianyu1350** [comment]
Hi,抱歉前几天数据更新的时候出现了疏忽, rel2id.json中缺失了关系，现已更新。你可以尝试用benchmark中的脚本重新下载数据集并测试。
