### ISSUE TITLE
opennre.get_model('wiki80_bert_softmax') issue

### ISSUE THREAD

**Issue by wangxinyi-gsafety** [thunlp/OpenNRE#306]
请问在运行get_model时报如下错误，是什么原因造成的？谢谢

model = opennre.get_model('wiki80_bert_softmax')
  File "d:\work\tools\opennre\opennre\pretrain.py", line 138, in get_model
    max_length=80, pretrain_path=os.path.join(root_path, 'pretrain\bert-base-uncased'))
  File "d:\work\tools\opennre\opennre\encoder\bert_encoder.py", line 20, in __init__
    self.bert = BertModel.from_pretrained(pretrain_path)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\modeling_utils.py", line 604, in from_pretrained
    **kwargs,
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\configuration_utils.py", line 200, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\configuration_utils.py", line 251, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'D:\Work\tools\OpenNRE\.opennre\pretraiert-base-uncased'. Make sure that:

- 'D:\Work\tools\OpenNRE\.opennre\pretraiert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'D:\Work\tools\OpenNRE\.opennre\pretraiert-base-uncased' is the correct path to a directory containing a config.json file

**Comment by wangxinyi-gsafety** [comment]
resolved

**Comment by aby-augustine** [comment]
i got similar one. how you resoled it

>>> import opennre
>>> model = opennre.get_model('wiki80_cnn_softmax')
2020-12-01 21:21:37,001 - root - INFO - Initializing word embedding with word2vec.
>>> model.infer({'text': 'He was the son of Máel Dúin mac Máele Fithrich, and grandson of the high king Áed Uaridnach (died 612).', 'h': {'pos': (18, 46)}, 't': {'pos': (78, 91)}})
Illegal instruction (core dumped)

**Comment by aby-augustine** [comment]
i'm  getting error for bert based model also. can anyone help resolving this.

>>> import opennre

>>> model = opennre.get_model('wiki80_bert_softmax')
2020-12-01 21:22:38,692 - root - INFO - Loading BERT pre-trained checkpoint.
2020-12-01 21:22:38,693 - transformers.configuration_utils - INFO - loading configuration file /home/aby/.opennre/pretrain/bert-base-uncased/config.json
2020-12-01 21:22:38,693 - transformers.configuration_utils - INFO - Model config BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

2020-12-01 21:22:38,694 - transformers.modeling_utils - INFO - loading weights file /home/aby/.opennre/pretrain/bert-base-uncased/pytorch_model.bin
2020-12-01 21:22:42,759 - transformers.modeling_utils - INFO - All model checkpoint weights were used when initializing BertModel.

2020-12-01 21:22:42,759 - transformers.modeling_utils - INFO - All the weights of BertModel were initialized from the model checkpoint at /home/aby/.opennre/pretrain/bert-base-uncased.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use BertModel for predictions without further training.
2020-12-01 21:22:42,760 - transformers.tokenization_utils_base - INFO - Model name '/home/aby/.opennre/pretrain/bert-base-uncased' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, TurkuNLP/bert-base-finnish-cased-v1, TurkuNLP/bert-base-finnish-uncased-v1, wietsedv/bert-base-dutch-cased). Assuming '/home/aby/.opennre/pretrain/bert-base-uncased' is a path, a model identifier, or url to a directory containing tokenizer files.
2020-12-01 21:22:42,776 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/.opennre/pretrain/bert-base-uncased/added_tokens.json. We won't load it.
2020-12-01 21:22:42,776 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/.opennre/pretrain/bert-base-uncased/special_tokens_map.json. We won't load it.
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/.opennre/pretrain/bert-base-uncased/tokenizer_config.json. We won't load it.
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/.opennre/pretrain/bert-base-uncased/tokenizer.json. We won't load it.
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - loading file /home/aby/.opennre/pretrain/bert-base-uncased/vocab.txt
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-01 21:22:42,778 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-01 21:22:42,778 - transformers.tokenization_utils_base - INFO - loading file None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aby/Desktop/OpenNRE/venv/lib/python3.8/site-packages/opennre-0.1-py3.8.egg/opennre/pretrain.py", line 140, in get_model
  File "/home/aby/Desktop/OpenNRE/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SoftmaxNN:
	Unexpected key(s) in state_dict: "sentence_encoder.bert.embeddings.position_ids".

**Comment by wangxinyi-gsafety** [comment]
My error happened in a windows platfrom, it seems os.path.join(root_path, 'pretrain\bert-base-uncased')) has returned a wrong value. I split this function as below:
pretrain_path=os.path.join(root_path, 'pretrain')
pretrain_path=os.path.join(pretrain_path, 'bert-base-uncased')
then it works.
