### ISSUE TITLE
in ubuntu Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by abyaug** [thunlp/OpenNRE#307]
i'm getting an error like this for cnn based model.
>>> import opennre
>>> model = opennre.get_model('wiki80_cnn_softmax')
2020-12-01 21:21:37,001 - root - INFO - Initializing word embedding with word2vec.
>>> model.infer({'text': 'He was the son of Máel Dúin mac Máele Fithrich, and grandson of the high king Áed Uaridnach (died 612).', 'h': {'pos': (18, 46)}, 't': {'pos': (78, 91)}})
Illegal instruction (core dumped)

for bert based model im getting like this.

>>> import opennre
^[[A
>>> model = opennre.get_model('wiki80_bert_softmax')
2020-12-01 21:22:38,692 - root - INFO - Loading BERT pre-trained checkpoint.
2020-12-01 21:22:38,693 - transformers.configuration_utils - INFO - loading configuration file /home/aby/.opennre/pretrain/bert-base-uncased/config.json
2020-12-01 21:22:38,693 - transformers.configuration_utils - INFO - Model config BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

2020-12-01 21:22:38,694 - transformers.modeling_utils - INFO - loading weights file /home/aby/.opennre/pretrain/bert-base-uncased/pytorch_model.bin
2020-12-01 21:22:42,759 - transformers.modeling_utils - INFO - All model checkpoint weights were used when initializing BertModel.

2020-12-01 21:22:42,759 - transformers.modeling_utils - INFO - All the weights of BertModel were initialized from the model checkpoint at /home/aby/.opennre/pretrain/bert-base-uncased.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use BertModel for predictions without further training.
2020-12-01 21:22:42,760 - transformers.tokenization_utils_base - INFO - Model name '/home/aby/.opennre/pretrain/bert-base-uncased' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, TurkuNLP/bert-base-finnish-cased-v1, TurkuNLP/bert-base-finnish-uncased-v1, wietsedv/bert-base-dutch-cased). Assuming '/home/aby/.opennre/pretrain/bert-base-uncased' is a path, a model identifier, or url to a directory containing tokenizer files.
2020-12-01 21:22:42,776 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/.opennre/pretrain/bert-base-uncased/added_tokens.json. We won't load it.
2020-12-01 21:22:42,776 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/.opennre/pretrain/bert-base-uncased/special_tokens_map.json. We won't load it.
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/.opennre/pretrain/bert-base-uncased/tokenizer_config.json. We won't load it.
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/.opennre/pretrain/bert-base-uncased/tokenizer.json. We won't load it.
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - loading file /home/aby/.opennre/pretrain/bert-base-uncased/vocab.txt
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-01 21:22:42,777 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-01 21:22:42,778 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-01 21:22:42,778 - transformers.tokenization_utils_base - INFO - loading file None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aby/Desktop/OpenNRE/venv/lib/python3.8/site-packages/opennre-0.1-py3.8.egg/opennre/pretrain.py", line 140, in get_model
  File "/home/aby/Desktop/OpenNRE/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SoftmaxNN:
	Unexpected key(s) in state_dict: "sentence_encoder.bert.embeddings.position_ids". 

im stuck at this for 2 days. can anyone help me resolve it. ASAP.

Thanks and regards

**Comment by gaotianyu1350** [comment]
This was due to the updated `transformers` package and we have updated the parameters. You can try to clean the cache folder `~/.opennre` folder and run again.

**Comment by abyaug** [comment]
> This was due to the updated `transformers` package and we have updated the parameters. You can try to clean the cache folder `~/.opennre` folder and run again.

i have cleared the system cache, for ubuntu which i'm using in virtualbox.
i have done installation in new virtualenv and changed the path for` .opennre`  folder to my project folder.
Still i'm getting the same error as mentioned .
![Screenshot from 2020-12-02 14-10-11](https://user-images.githubusercontent.com/71558896/100850013-32b87980-34a9-11eb-8d56-63e4839059b2.png)

**Comment by wangxinyi-gsafety** [comment]
@ gaotianyu1350, after we clean the cache folder .opennre, do we need to rerun the download script for wiki80 dataset to avoid the below error?

raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SoftmaxNN:
Unexpected key(s) in state_dict: "sentence_encoder.bert.embeddings.position_ids".

**Comment by gaotianyu1350** [comment]
This is weird. Maybe you can try to manually download the model `https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/pretrain/nre/{model_name}.pth.tar` and put it in `~/.opennre/pretrain/nre/`. Also make sure you pull the latest commit.

**Comment by wangxinyi-gsafety** [comment]
@gaotianyu1350, i have followed the step above you provided, but unfortunately, still the same issue happened, this is the stack:

2020-12-03 10:25:14,305 - transformers.modeling_utils - INFO - loading weights file D:\Work\tools\OpenNRE\.opennre\pretrain\bert-base-uncased\pytorch_model.bin
2020-12-03 10:25:19,903 - transformers.modeling_utils - INFO - All model checkpoint weights were used when initializing BertModel.

2020-12-03 10:25:19,906 - transformers.modeling_utils - INFO - All the weights of BertModel were initialized from the model checkpoint at D:\Work\tools\OpenNRE\.opennre\pretrain\bert-base-uncased.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use BertModel for predictions without further training.
2020-12-03 10:25:19,912 - transformers.tokenization_utils_base - INFO - Model name 'D:\Work\tools\OpenNRE\.opennre\pretrain\bert-base-uncased' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, TurkuNLP/bert-base-finnish-cased-v1, TurkuNLP/bert-base-finnish-uncased-v1, wietsedv/bert-base-dutch-cased). Assuming 'D:\Work\tools\OpenNRE\.opennre\pretrain\bert-base-uncased' is a path, a model identifier, or url to a directory containing tokenizer files.
2020-12-03 10:25:19,920 - transformers.tokenization_utils_base - INFO - Didn't find file D:\Work\tools\OpenNRE\.opennre\pretrain\bert-base-uncased\added_tokens.json. We won't load it.
2020-12-03 10:25:19,922 - transformers.tokenization_utils_base - INFO - Didn't find file D:\Work\tools\OpenNRE\.opennre\pretrain\bert-base-uncased\special_tokens_map.json. We won't load it.
2020-12-03 10:25:19,930 - transformers.tokenization_utils_base - INFO - Didn't find file D:\Work\tools\OpenNRE\.opennre\pretrain\bert-base-uncased\tokenizer_config.json. We won't load it.
2020-12-03 10:25:19,943 - transformers.tokenization_utils_base - INFO - Didn't find file D:\Work\tools\OpenNRE\.opennre\pretrain\bert-base-uncased\tokenizer.json. We won't load it.
2020-12-03 10:25:19,950 - transformers.tokenization_utils_base - INFO - loading file D:\Work\tools\OpenNRE\.opennre\pretrain\bert-base-uncased\vocab.txt
2020-12-03 10:25:19,956 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-03 10:25:19,965 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-03 10:25:19,970 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-03 10:25:19,983 - transformers.tokenization_utils_base - INFO - loading file None
Traceback (most recent call last):
  File "opennrewrapper.py", line 9, in <module>
    model = opennre.get_model('wiki80_bert_softmax')
  File "d:\work\tools\opennre\opennre\pretrain.py", line 145, in get_model
    m.load_state_dict(torch.load(ckpt, map_location='cpu')['state_dict'])
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SoftmaxNN:
        Unexpected key(s) in state_dict: "sentence_encoder.bert.embeddings.position_ids".

**Comment by gaotianyu1350** [comment]
What is your transformers version?

**Comment by wangxinyi-gsafety** [comment]
transformers version is 3.0.2
transformers in c:\users\wang\appdata\local\programs\python\python37\lib\site-packages (3.0.2)

**Comment by gaotianyu1350** [comment]
Maybe try to upgrade transformers to the latest version (or 3.4.0, which is the version I use).

**Comment by wangxinyi-gsafety** [comment]
@gaotianyu1350, thanks. this issue has been resolved after upgrade the transformers verison. 
But when I run the model.infer(), another problem comes:

Traceback (most recent call last):
  File "opennrewrapper.py", line 11, in <module>
    'h': {'pos': (18, 46)}, 't': {'pos': (78, 91)}})
  File "d:\work\tools\opennre\opennre\model\softmax_nn.py", line 31, in infer
    logits = self.forward(*item)
  File "d:\work\tools\opennre\opennre\model\softmax_nn.py", line 46, in forward
    rep = self.drop(rep)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "C:\Users\Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\functional.py", line 973, in dropout
    else _VF.dropout(input, p, training))
TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str

**Comment by wangxinyi-gsafety** [comment]
@gaotianyu1350, above issue resolved after I downgrade the transformers version from 4.1 to 3.4.0, thanks.

**Comment by abyaug** [comment]
@wangxinyi-gsafety i have the same issue that you had.
2020-12-03 18:24:49,567 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/Desktop/Opennre/OpenNRE/.opennre/pretrain/bert-base-uncased/added_tokens.json. We won't load it.
2020-12-03 18:24:49,567 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/Desktop/Opennre/OpenNRE/.opennre/pretrain/bert-base-uncased/special_tokens_map.json. We won't load it.
2020-12-03 18:24:49,567 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/Desktop/Opennre/OpenNRE/.opennre/pretrain/bert-base-uncased/tokenizer_config.json. We won't load it.
2020-12-03 18:24:49,567 - transformers.tokenization_utils_base - INFO - Didn't find file /home/aby/Desktop/Opennre/OpenNRE/.opennre/pretrain/bert-base-uncased/tokenizer.json. We won't load it.
2020-12-03 18:24:49,567 - transformers.tokenization_utils_base - INFO - loading file /home/aby/Desktop/Opennre/OpenNRE/.opennre/pretrain/bert-base-uncased/vocab.txt
2020-12-03 18:24:49,567 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-03 18:24:49,568 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-03 18:24:49,568 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-03 18:24:49,568 - transformers.tokenization_utils_base - INFO - loading file None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aby/Desktop/Opennre/OpenNRE/opennre/pretrain.py", line 140, in get_model
    m.load_state_dict(torch.load(ckpt, map_location='cpu')['state_dict'])
  File "/home/aby/Desktop/Opennre/nre/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SoftmaxNN:
	Unexpected key(s) in state_dict: "sentence_encoder.bert.embeddings.position_ids". 



@wangxinyi-gsafety can u please provide the steps that u followed after this. it would be really helpful.i've been stuck at this for a while !
Thanks and regards.

**Comment by abyaug** [comment]
@gaotianyu1350 @wangxinyi-gsafety got it....updated transformers to version 3.4.0. Its working!
