### ISSUE TITLE
Unable to download Bert models

### ISSUE THREAD

**Issue by aishwaryanr** [thunlp/OpenNRE#312]
I'm getting this error when I run get_model for any of the Bert based models

2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - Didn't find file /home/ubuntu/.opennre/pretrain/bert-base-uncased/added_tokens.json. We won't load it.
2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - Didn't find file /home/ubuntu/.opennre/pretrain/bert-base-uncased/special_tokens_map.json. We won't load it.
2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - Didn't find file /home/ubuntu/.opennre/pretrain/bert-base-uncased/tokenizer_config.json. We won't load it.
2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - Didn't find file /home/ubuntu/.opennre/pretrain/bert-base-uncased/tokenizer.json. We won't load it.
2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file /home/ubuntu/.opennre/pretrain/bert-base-uncased/vocab.txt
2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file None
2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/OpenNRE/opennre/pretrain.py", line 140, in get_model
    m.load_state_dict(torch.load(ckpt, map_location='cpu')['state_dict'])
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SoftmaxNN:
	Unexpected key(s) in state_dict: "sentence_encoder.bert.embeddings.position_ids". 

I tried the solution posted in issue #306 but no luck

**Comment by abyaug** [comment]
> I'm getting this error when I run get_model for any of the Bert based models
> 
> 2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - Didn't find file /home/ubuntu/.opennre/pretrain/bert-base-uncased/added_tokens.json. We won't load it.
> 2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - Didn't find file /home/ubuntu/.opennre/pretrain/bert-base-uncased/special_tokens_map.json. We won't load it.
> 2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - Didn't find file /home/ubuntu/.opennre/pretrain/bert-base-uncased/tokenizer_config.json. We won't load it.
> 2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - Didn't find file /home/ubuntu/.opennre/pretrain/bert-base-uncased/tokenizer.json. We won't load it.
> 2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file /home/ubuntu/.opennre/pretrain/bert-base-uncased/vocab.txt
> 2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file None
> 2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file None
> 2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file None
> 2020-12-17 23:30:06,840 - transformers.tokenization_utils_base - INFO - loading file None
> Traceback (most recent call last):
> File "", line 1, in
> File "/home/ubuntu/OpenNRE/opennre/pretrain.py", line 140, in get_model
> m.load_state_dict(torch.load(ckpt, map_location='cpu')['state_dict'])
> File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for SoftmaxNN:
> Unexpected key(s) in state_dict: "sentence_encoder.bert.embeddings.position_ids".
> 
> I tried the solution posted in issue #306 but no luck

I had this issue. remove the existing transformers and pip install transformers==3.4.0
