### ISSUE TITLE
bag_attention with bert cls features error

### ISSUE THREAD

**Issue by AlexRainHao** [thunlp/OpenNRE#339]
## Background

It seems like training procedure using `bag_attention` where features obtained from `bert cls`, where argument of `pooler` set to `cls`, would raise error

## Error

```
Traceback (most recent call last):
  File "example/train_bag_bert.py", line 143, in <module>
    framework.train_model(args.metric)
  File "/home/user/yuanyh/Example/OpenNRE-master/opennre/framework/bag_re.py", line 121, in train_model
    logits = self.model(label, scope, *args, bag_size=self.bag_size)
  File "/home/user/yuanyh/vitualEnv/base_dl/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/yuanyh/vitualEnv/base_dl/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/yuanyh/vitualEnv/base_dl/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'pos2'
```

## Arguments

```bash
python3 example/train_bag_bert.py \
    --pretrain_path ./pretrain/bert-base-uncased \
    --ckpt nyt10m-bert \
    --pooler cls \
    --metric micro_f1 \
    --train_file ./benchmark/nyt10m/nyt10m_train.txt \
    --train_file ./benchmark/nyt10m/nyt10m_train.txt \
    --val_file ./benchmark/nyt10m/nyt10m_val.txt \
    --test_file ./benchmark/nyt10m/nyt10m_test.txt \
    --rel2id_file ./benchmark/nyt10m/nyt10m_rel2id.json \
    --batch_size 16 \
    --lr 2e-5 \
    --max_length 128 \
    --max_epoch 3 \
    --aggr att \
    --seed 2021
```

## Related

BertEncoder: line 96
BagAttention(BagRE): line 68

## Problem

There no exist features of `pos1, pos2` extracted by `BertEncoder.tokenize`

**Comment by GanjinZero** [comment]
same issue here

**Comment by QiaoZiqing** [comment]
Thanks for pointing out this bug.
BagAttention requires pos1 and pos2, but BertEncoder.tokenize does not provide these two parameters(Because these two parameters are actually not needed for `cls` ), we modified the code and added pos1 and pos2 as the return value of bagencoder.
