### ISSUE TITLE
相对路径下的opennre无法使用，但报错显示的文件并不存在。

### ISSUE THREAD

**Issue by 33kaopu** [thunlp/OpenNRE#369]
Traceback (most recent call last):
  File "example/train.py", line 155, in <module>
    framework.train_model('micro_f1')  #???  有问题！
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/opennre-0.1-py3.8.egg/opennre/framework/sentence_re.py", line 133, in train_model
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/opennre-0.1-py3.8.egg/opennre/model/softmax_nn.py", line 46, in forward
    rep = self.sentence_encoder(*args)  # (B, H)
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangyue/anaconda3/envs/pytorch_2/lib/python3.8/site-packages/opennre-0.1-py3.8.egg/opennre/encoder/bert_encoder.py", line 164, in forward
    pic = pic.view(-1, 10, self.pic_feat)
RuntimeError: shape '[-1, 10, 4096]' is invalid for input of size 237568

**Comment by THUCSTHanxu13** [comment]
你这个贴出来的没有办法反应问题，麻烦提供更多细节
