### ISSUE TITLE
转JSON数据问题

### ISSUE THREAD

**Issue by 598807302** [thunlp/OpenNRE#99]
当我运行python protobuf2json.py .
报错
Loading entities...
Finish loading, got 1845262 entities totally
Loading ./kb_manual/trainPositive.pb
Finish loading, got 121867 instances and 19465 relfacts totally
Loading ./kb_manual/trainNegative.pb
Traceback (most recent call last):
  File "protobuf2json.py", line 75, in <module>
    main()
  File "protobuf2json.py", line 52, in main
    get_instances(ori_train_json_data, os.path.join(root_dir, 'kb_manual/trainNegative.pb'))
  File "protobuf2json.py", line 34, in get_instances
    relfact.ParseFromString(msg_buf)
google.protobuf.message.DecodeError: Error parsing message

**Comment by 598807302** [comment]
NYT数据集没下载完 解决了
